#!/bin/bash

cd $(dirname "$0")
config_dir=${PWD##$HOME/}

check_commands() {
	local missing=0
	for tool in "$@"; do
		if ! type "$tool" > /dev/null; then
			echo "$tool missing."
			missing=1
		fi
	done
	return $missing
}

config_backup_dir="backup-$(date +%F-%H-%M-%S)";

install_file() {
	if [ -e "$HOME/$2" ]; then
		if [ "$(readlink "$HOME/$2")" != "$config_dir/$1" ]; then
			mkdir -p "$config_backup_dir"
			mv "$HOME/$2" "$config_backup_dir/$1"
			echo "'$2' already exists. It is moved to '$config_dir/$config_backup_dir/$1'." 1>&2
		fi
	fi
	ln -fs "$config_dir/$1" "$HOME/$2"
}

# Check for required tools.
required_commands="git vim"
if ! check_commands $required_commands; then
	exit 1;
fi

# Install configuration files.
for file in aliases bashrc dircolors gitconfig gitignore profile screenrc vimrc zshrc vim zprofile shellrc Xresources
do
	install_file "$file" ".$file"
done

# Install vundle.
if [ ! -d "vim/bundle/vundle" ]; then
	mkdir -p "vim/bundle"
	git clone https://github.com/gmarik/vundle.git "vim/bundle/vundle"
fi
vim +BundleClean +BundleInstall +qall
